### ISSUE TITLE
problems with shipping and payment

### ISSUE THREAD

**Issue by fgiering** [shopwareLabs/SwagMigrationMagento#19]
I need to migrate data from a two-store-magento 1.9 and it seems like the migration...
- cant handle if one store is set to "free shipping" in magento
- the payment methods are not all listed in the pre-mapping: I get the warning "Cannot find payment_method" in the migration-log. Than I cant open the orders in shopware. Console error: "transaction is null".

Is this known to you?

**Comment by htkassner** [comment]
I created an issue for this topic as we will close the issues section under this project. https://issues.shopware.com/issues/MIG-208. We´ll have a look at it.
