### ISSUE TITLE
TypeError for media migration

### ISSUE THREAD

**Issue by sobyte** [shopwareLabs/SwagMigrationMagento#5]
When migrating media via the messenger I'm getting following error message:
```
The handler "SwagMigrationAssistant\Migration\MessageQueue\Handler\ProcessMediaHandler" threw a "TypeError" for message "SwagMigrationAssistant\Migration\MessageQueue\Message\ProcessMediaMessage". The Exception was "Argument 1 passed to Shopware\Core\Framework\Uuid\Uuid::fromHexToBytes() must be of the type string, integer given, called in web/vendor/shopware/core/Framework/DataAbstractionLayer/Write/EntityWriter.php on line 121.
```

The trace showed that the error occurs here 
https://github.com/shopwareLabs/SwagMigrationMagento/blob/101705525147b4aa7eadb11d2bb43b37b6e84775/src/Profile/Magento/Media/LocalMediaProcessor.php#L245
because of the missing array key https://github.com/shopwareLabs/SwagMigrationMagento/blob/101705525147b4aa7eadb11d2bb43b37b6e84775/src/Profile/Magento/Media/LocalMediaProcessor.php#L355 
See following reference which doesn't throw an error https://github.com/shopwareLabs/SwagMigrationMagento/blob/101705525147b4aa7eadb11d2bb43b37b6e84775/src/Profile/Magento/Media/LocalMediaProcessor.php#L189

**Comment by htkassner** [comment]
Thank you @sobyte . We will merge a commit in the next hour I guess which removes this code. So this won´t be an issue anymore then
