### ISSUE TITLE
Can't create a connection without a password

### ISSUE THREAD

**Issue by peterjaap** [shopwareLabs/SwagMigrationMagento#9]
I'm trying to create a connection but when I leave the password field empty, I can't click "Connect":

![image](https://user-images.githubusercontent.com/431360/82078658-cbd89c00-96e1-11ea-9586-7ce1c64bf609.png)

I don't use passwords on my local machine so it would be great of a passwordless option can be made.

**Comment by mitelg** [comment]
fixed with #10
